sudo: required
service:
  - docker
before_install:
  - docker build -t josephmbassey/react-docker-deployment -f Dockerfile.dev .
script:
  - docker run josephmbassey/react-docker-deployment npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker-deployment"
  env: "ReactDockerDeployment-env"
  bucket_name: "elasticbeanstalk-us-east-1-773213525064"
  bucket_path: "react-docker-deployment"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"